export const shopData = [
  {
    id: "1",
    name: "White Asiatic Lilies",
    category: "Sympathy and Condolence",
    prices: {
      small: 1500,
      medium: 2000,
      large: 2500,
      extraLarge: 3000,
    },
    image: "/arrangements-in-vases-boxes/flower28.jpeg",
    images: [
      "/arrangements-in-vases-boxes/flower28.jpeg",
      "/arrangements-in-vases-boxes/flower28.jpeg",
    ],
    inStock: true,
    stock: 25,
    rating: 5,
    tags: ["sympathy", "condolence", "peaceful", "white", "elegant"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "small",
    description:
      "A graceful sympathy table arrangement designed to express heartfelt condolences. Featuring soft, elegant blooms in calming tones, it offers comfort, peace, and a gentle reminder of love and remembrance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "White Chrysanthemums",
    category: "Sympathy and Condolence",
    prices: {
      small: 1500,
      medium: 2000,
      large: 2500,
      extraLarge: 3000,
    },
    image: "/arrangements-in-vases-boxes/flower27.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["sympathy", "condolence", "peaceful", "white", "elegant"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "small",
    description:
      "A graceful sympathy table arrangement designed to express heartfelt condolences. Featuring soft, elegant blooms in calming tones, it offers comfort, peace, and a gentle reminder of love and remembrance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "Daily Blossoms",
    category: "Everyday",
    prices: {
      small: 800,
      medium: 1000,
      large: 1500,
    },
    image: "/arrangements-in-vases-boxes/flower16.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["everyday", "bright", "cheerful", "casual", "fresh", "colorful"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red,pink,white",
    size: "medium",
    description:
      "A joyful mix of fresh blooms, perfect for brightening up your home, office, or gifting on any occasion. These everyday flowers bring color, warmth, and happiness into every moment.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    name: "Peaceful Memories",
    category: "Sympathy and Condolence",
    price: 1200,
    image: "/arrangements-in-vases-boxes/flower30.jpeg",
    inStock: true,
    stock: 10,
    rating: 5,
    tags: ["sympathy", "condolence", "comfort", "serenity", "white-lilies"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A serene condolence arrangement crafted with delicate white lilies and soft greenery. This elegant design conveys comfort, peace, and heartfelt support during times of loss, offering a gentle tribute of remembrance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    name: "Sweet Embrace Flower",
    category: "Love and Romance",
    prices: {
      small: 400,
      medium: 2000,
      large: 1000,
      extraLarge: 1500,
    },
    image: "/arrangements-in-vases-boxes/flower24.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "small",
    description:
      "A delicate arrangement of soft pink blooms, capturing the beauty of tenderness and affection. An ideal gift to express sweet emotions and celebrate heartfelt connections.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    name: "Eternal Love",
    category: "Love and Romance",
    prices: {
      small: 500,
      medium: 700,
      large: 1000,
      extraLarge: 1500,
    },
    image: "/arrangements-in-vases-boxes/flower11.jpeg",
    inStock: true,
    stock: 10,
    rating: 5,
    tags: ["love", "romantic", "red", "roses", "anniversary", "valentine"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "small",
    description:
      "An elegant floral arrangement symbolizing loyalty and devotion. With every bloom, it whispers the promise of everlasting love a classic choice for anniversaries or proposals.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    name: "Passion Blooms",
    category: "Love and Romance",
    price: 1500,
    image: "/Wreath/wreath-flower12.jpeg",
    inStock: true,
    stock: 10,
    rating: 5,
    tags: [
      "romantic",
      "vibrant",
      "luxury",
      "roses",
      "celebration",
      "deep-love",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A luxurious mix of bold, romantic flowers bursting with color and life. This bouquet embodies deep emotions, making it the perfect gesture for celebrating love and passion.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    name: "Forever Yours",
    category: "Love and Romance",
    price: 1800,
    image: "/arrangements-in-vases-boxes/flower49.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: [
      "romantic",
      "vibrant",
      "luxury",
      "roses",
      "celebration",
      "deep-love",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "An elegant floral arrangement symbolizing loyalty and devotion. With every bloom, it whispers the promise of everlasting love a classic choice for anniversaries or proposals.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9",
    name: "Eternal Love",
    category: "Love and Romance",
    price: 1800,
    image: "/arrangements-in-vases-boxes/flower20.jpeg",
    inStock: true,
    stock: 10,
    rating: 5,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "large",
    description:
      "A timeless bouquet of radiant red roses, the ultimate symbol of passion and devotion. Perfect for anniversaries, Valentine’s Day, or to remind someone special that your love is forever.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "10",
    name: "Glass of Romance",
    category: "Love and Romance",
    price: 1200,
    image: "/arrangements-in-vases-boxes/flower50.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A classic arrangement of 12 long-stemmed red roses, perfect for expressing love and romance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "11",
    name: "Bound by Love",
    category: "Love and Romance",
    price: 3000,
    image: "/arrangements-in-vases-boxes/flower22.jpeg",
    inStock: true,
    stock: 20,
    rating: 5,
    tags: ["romance", "affection", "pink", "roses", "tender", "heartfelt"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "large",
    description:
      "A timeless bouquet of radiant red roses, the ultimate symbol of passion and devotion. Perfect for anniversaries, Valentine's Day, or to remind someone special that your love is forever.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "12",
    name: "Rose in Time",
    category: "Love and Romance",
    price: 1200,
    image: "/arrangements-in-vases-boxes/flower31.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A classic arrangement of 12 long-stemmed red roses, perfect for expressing love and romance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "13",
    name: "Sweetheart Bloom Box",
    category: "Love and Romance",
    price: 800,
    image: "/arrangements-in-vases-boxes/flower32.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: [
      "love",
      "romantic",
      "roses",
      "toffee",
      "heart-shape",
      "valentine",
      "anniversary",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A delightful arrangement of fresh love flowers paired with sweet toffees, presented in an elegant heart-shaped container. This romantic gift is perfect for Valentine's Day, anniversaries, or any special moment when you want to express love in the sweetest way possible.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "14",
    name: "Passion Blooms",
    category: "Love and Romance",
    price: 1800,
    image: "/arrangements-in-vases-boxes/flower33.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["romantic", "classic", "red", "roses"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A joyful bouquet of mixed romantic blooms, full of color and charm. Perfect for brightening your partner's day and celebrating love in its most beautiful form.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "15",
    name: "Basket of Love",
    category: "Love and Romance",
    price: 1000,
    image: "/arrangements-in-vases-boxes/flower34.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: [
      "love",
      "romantic",
      "basket",
      "roses",
      "anniversary",
      "valentine",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A charming basket filled with fresh romantic blooms, designed to express deep love and affection. Perfect for anniversaries, Valentine’s Day, or simply surprising someone special, this arrangement beautifully combines elegance and heartfelt emotion.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "16",
    name: "Timeless Love",
    category: "Love and Romance",
    price: 1000,
    image: "/arrangements-in-vases-boxes/flower35.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: [
      "love",
      "romantic",
      "rose",
      "glass",
      "timeless",
      "anniversary",
      "valentine",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "small",
    description:
      "A timeless bouquet of radiant red roses, the ultimate symbol of passion and devotion. Perfect for anniversaries, Valentine's Day, or to remind someone special that your love is forever.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "17",
    name: "Love & Sweetness",
    category: "Love and Romance",
    price: 2500,
    image: "/arrangements-in-vases-boxes/flower36.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A stunning single rose encased in an elegant glass container the ultimate symbol of timeless love and devotion. Perfect for anniversaries, Valentine's Day, or as a romantic keepsake, this beautiful piece captures the magic of love that lasts forever.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "18",
    name: "Fruit basket with Love Flower",
    category: "Love and Romance",
    price: 800,
    image: "/arrangements-in-vases-boxes/flower37.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A delightful arrangement of fresh love flowers paired with seasonal fruits, presented in an elegant basket. This romantic gift is perfect for Valentine's Day, anniversaries, or any special moment when you want to express love in the sweetest way possible.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "19",
    name: "Forever Yours",
    category: "Love and Romance",
    price: 1200,
    image: "/arrangements-in-vases-boxes/flower48.jpeg",
    inStock: true,
    stock: 25,
    rating: 5,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "An elegant floral arrangement symbolizing loyalty and devotion. With every bloom, it whispers the promise of everlasting love a classic choice for anniversaries or proposals.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "20",
    name: "Elegant Event Blooms",
    category: "Event and Decor",
    price: 1000,
    image: "/arrangements-in-vases-boxes/flower39.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: [
      "event",
      "decor",
      "elegant",
      "arrangement",
      "celebration",
      "wedding",
      "party",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A sophisticated floral arrangement crafted to enhance any event or celebration. With elegant blooms and stylish design, these flowers add beauty and charm to weddings, parties, and special gatherings.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "21",
    name: "Romance in Bloom",
    category: "Love and Romance",
    price: 2000,
    image: "/arrangements-in-vases-boxes/flower47.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A luxurious mix of bold, romantic flowers bursting with color and life. This bouquet embodies deep emotions, making it the perfect gesture for celebrating love and passion.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "22",
    name: "Heartfelt Circle",
    category: "Love and Romance",
    price: 1500,
    image: "/bouquets/bouquet-flower47.jpeg",
    inStock: true,
    stock: 25,
    rating: 5,
    tags: [
      "love",
      "romantic",
      "wreath",
      "roses",
      "anniversary",
      "valentine",
      "eternal",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red,pink",
    size: "medium",
    description:
      "A stunning love wreath beautifully arranged in a timeless circular design, symbolizing eternal romance and devotion. Adorned with elegant blooms, it is the perfect piece to celebrate anniversaries, Valentine’s Day, or any moment that honors everlasting love.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "23",
    name: "Love in Bloom",
    category: "Love and Romance",
    price: 1500,
    image: "/Wreath/wreath-flower15.jpeg",
    inStock: true,
    stock: 25,
    rating: 5,
    tags: [
      "love",
      "romantic",
      "wreath",
      "roses",
      "anniversary",
      "valentine",
      "eternal",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A stunning love wreath beautifully arranged in a timeless circular design, symbolizing eternal romance and devotion. Adorned with elegant blooms, it is the perfect piece to celebrate anniversaries, Valentine’s Day, or any moment that honors everlasting love.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "24",
    name: "Birthday Blooms",
    category: "Birthday",
    price: 2500,
    image: "/arrangements-in-vases-boxes/flower40.JPG",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["birthday", "elegant", "luxury", "roses", "celebration", "special"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A sophisticated floral arrangement crafted with elegance and charm. Perfect for milestone birthdays or when you want to celebrate in style, this bouquet adds a touch of luxury to their special day.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "25",
    name: "Birthday Blossoms",
    category: "Birthday",
    price: 2200,
    image: "/arrangements-in-vases-boxes/flower1.jpg",
    inStock: true,
    stock: 25,
    rating: 5,
    tags: [
      "birthday",
      "celebration",
      "classic",
      "bouquet",
      "colorful",
      "fresh",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "large",
    description:
      "A cheerful bouquet of fresh blooms designed to brighten any birthday celebration. With vibrant colors and a joyful arrangement, these flowers are the perfect way to say “Happy Birthday” and make their day unforgettable.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "26",
    name: "Birthday Elegance",
    category: "Birthday",
    price: 2500,
    image: "/arrangements-in-vases-boxes/flower29.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: [
      "birthday",
      "celebration",
      "classic",
      "bouquet",
      "colorful",
      "fresh",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "A sophisticated floral arrangement crafted with elegance and charm. Perfect for milestone birthdays or when you want to celebrate in style, this bouquet adds a touch of luxury to their special day.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "27",
    name: "Birthday Blossoms",
    category: "Birthday",
    price: 2000,
    image: "/arrangements-in-vases-boxes/flower52.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["birthday", "elegant", "luxury", "roses", "celebration", "special"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "A lively arrangement bursting with color and, just like a birthday should be! Perfect for surprising someone special, these birthday flowers bring joy, laughter, and heartfelt wishes in every bloom.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "28",
    name: "Birthday Elegance",
    category: "Birthday",
    price: 2500,
    image: "/arrangements-in-vases-boxes/flower53.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["birthday", "elegant", "luxury", "roses", "celebration", "special"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "A lively arrangement bursting with color and energy,just like a birthday should be! Perfect for surprising someone special, these birthday flowers bring joy, laughter, and heartfelt wishes in every bloom.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "29",
    name: "Birthday Elegance",
    category: "Birthday",
    price: 2500,
    image: "/bouquets/bouquet-flower36.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["birthday", "elegant", "luxury", "roses", "celebration", "special"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "A sophisticated floral arrangement crafted with elegance and charm. Perfect for milestone birthdays or when you want to celebrate in style, this bouquet adds a touch of luxury to their special day.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "30",
    name: "Daily Blossoms",
    category: "Everyday",
    price: 1000,
    image: "/arrangements-in-vases-boxes/flower18.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["birthday", "elegant", "luxury", "roses", "celebration", "special"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "A joyful mix of fresh blooms, perfect for brightening up your home, office, or gifting on any occasion. These everyday flowers bring color, warmth, and happiness into every moment.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "31",
    name: "Birthday Blossoms",
    category: "Birthday",
    price: 1800,
    image: "/arrangements-in-vases-boxes/flower23.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["birthday", "fun", "cheerful", "colorful", "surprise", "gift"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "A lively arrangement bursting with color and energy, just like a birthday should be! Perfect for surprising someone special, these birthday flowers bring joy, laughter, and heartfelt wishes in every bloom.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "32",
    name: "Bloom & Brighten",
    category: "Everyday",
    prices: {
      small: 600,
      medium: 900,
      large: 1200,
    },
    image: "/Fresh-Flower/fresh-flower16.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["everyday", "flowers", "bright", "mixed", "gift", "uplifting"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink,white",
    size: "small",
    description:
      "An uplifting bouquet of mixed flowers that adds a touch of beauty to daily life. Perfect for any occasion or just because, these blooms bring light and happiness to every space.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "34",
    name: "Décor Charm Bouquet",
    category: "Event and Decor",
    price: 2000,
    image: "/arrangements-in-vases-boxes/flower45.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["decor", "event", "stylish", "flowers", "arrangement", "luxury"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "green,pink",
    size: "medium",
    description:
      "A graceful arrangement designed to elevate spaces with timeless beauty. Perfect for home décor, office styling, or event decoration, these flowers bring elegance and warmth to any setting.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "35",
    name: "Blooming Success",
    category: "Congratulations",
    price: 2000,
    image: "/arrangements-in-vases-boxes/flower15.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: [
      "congratulations",
      "celebration",
      "success",
      "vibrant",
      "colorful",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "A vibrant bouquet bursting with lively colors, designed to celebrate achievements and milestones. Perfect for graduations, promotions, or any joyful occasion, these blooms say “Congratulations” in the brightest way.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "36",
    name: "Cheers in Bloom",
    category: "Congratulations",
    price: 1500,
    image: "/arrangements-in-vases-boxes/flower17.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: [
      "congratulations",
      "celebration",
      "success",
      "vibrant",
      "colorful",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "A vibrant bouquet bursting with lively colors, designed to celebrate achievements and milestones. Perfect for graduations, promotions, or any joyful occasion, these blooms say “Congratulations” in the brightest way.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "37",
    name: "White Lilies Sympathy Arrangement",
    category: "Sympathy and Condolence",
    price: 1500,
    image: "/arrangements-in-vases-boxes/flower10.jpg",
    inStock: true,
    stock: 25,
    rating: 5,
    tags: ["sympathy", "condolence", "peaceful", "white", "elegant"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "large",
    description:
      "A graceful sympathy table arrangement designed to express heartfelt condolences. Featuring soft, elegant blooms in calming tones, it offers comfort, peace, and a gentle reminder of love and remembrance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "38",
    name: "Daily Blossoms",
    category: "Everyday",
    price: 1000,
    image: "/arrangements-in-vases-boxes/flower2.jpg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "A classic arrangement of 12 long-stemmed red roses, perfect for expressing love and romance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "39",
    name: "Décor Charm Bouquet",
    category: "Event and Decor",
    price: 1200,
    image: "/arrangements-in-vases-boxes/flower12.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["decor", "event", "stylish", "flowers", "arrangement", "luxury"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "yellow,green",
    size: "medium",
    description:
      "A graceful arrangement designed to elevate spaces with timeless beauty. Perfect for home décor, office styling, or event decoration, these flowers bring elegance and warmth to any setting.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "40",
    name: "Gentle Remembrance",
    category: "Sympathy and Condolence",
    prices: {
      small: 700,
      medium: 1000,
      large: 1200,
    },
    image: "/bouquets/bouquet-flower18.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["sympathy", "condolence", "comfort", "serenity", "white-lilies"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "greenish-white",
    size: "medium",
    description:
      "A serene condolence arrangement crafted with delicate white lilies and soft greenery. This elegant design conveys comfort, peace, and heartfelt support during times of loss, offering a gentle tribute of remembrance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "41",
    name: "Décor Charm",
    category: "Everyday",
    price: 1000,
    image: "/arrangements-in-vases-boxes/flower25.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["decor", "event", "stylish", "flowers", "arrangement", "luxury"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "light-pink,white",
    size: "medium",
    description:
      "A graceful arrangement designed to elevate spaces with timeless beauty. Perfect for home décor, office styling, or event decoration, these flowers bring elegance and warmth to any setting.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "42",
    name: "Daily Blossoms",
    category: "Everyday",
    price: 2000,
    image: "/bouquets/bouquet-flower46.jpeg",
    inStock: true,
    stock: 10,
    rating: 5,
    tags: ["everyday", "cheerful", "bright", "casual", "colorful", "fresh"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "purple",
    size: "large",
    description:
      "A joyful mix of fresh blooms, perfect for brightening up your home, office, or gifting on any occasion. These everyday flowers bring color, warmth, and happiness into every moment.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "43",
    name: "Red Roses",
    category: "Love and Romance",
    price: 1000,
    image: "/bouquets/bouquet-flower35.jpeg",
    inStock: true,
    stock: 10,
    rating: 5,
    tags: ["love", "romantic", "roses", "red", "valentine", "anniversary"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "large",
    description:
      "A timeless bouquet of elegant roses, symbolizing love, passion, and devotion. Perfect for anniversaries, Valentine’s Day, or any special moment when words are not enough to express the depth of your feelings.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "44",
    name: "Red Roses",
    category: "Love and Romance",
    price: 1500,
    image: "/bouquets/bouquet-flower27.jpeg",
    inStock: true,
    stock: 25,
    rating: 5,
    tags: ["love", "romantic", "roses", "red", "valentine", "anniversary"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "small",
    description:
      "A timeless bouquet of elegant roses, symbolizing love, passion, and devotion. Perfect for anniversaries, Valentine's Day, or any special moment when words are not enough to express the depth of your feelings.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "45",
    name: "Hearts in Bloom",
    category: "Love and Romance",
    price: 1200,
    image: "/Wreath/wreath-flower17.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "large",
    description:
      "A joyful bouquet of mixed romantic blooms, full of color and charm. Perfect for brightening your partner’s day and celebrating love in its most beautiful form.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "46",
    name: "Eternal Rose",
    category: "Love and Romance",
    price: 800,
    image: "/bouquets/bouquet-flower21.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "An elegant floral arrangement symbolizing loyalty and devotion. With every bloom, it whispers the promise of everlasting love a classic choice for anniversaries or proposals.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "47",
    name: "Romantic Radiance",
    category: "Love and Romance",
    price: 1200,
    image: "/bouquets/bouquet-flower41.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A luxurious mix of bold, romantic flowers bursting with color and life. This bouquet embodies deep emotions, making it the perfect gesture for celebrating love and passion.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "48",
    name: "Birthday Elegance",
    category: "Birthday",
    price: 1000,
    image: "/bouquets/bouquet-flower6.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["birthday", "fun", "cheerful", "colorful", "surprise", "gift"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "large",
    description:
      "A lively arrangement bursting with color and energy, just like a birthday should be! Perfect for surprising someone special, these birthday flowers bring joy, laughter, and heartfelt wishes in every bloom.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "49",
    name: "Birthday Elegance",
    category: "Birthday",
    prices: {
      small: 800,
      medium: 1000,
      large: 1500,
    },
    image: "/bouquets/bouquet-flower25.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["birthday", "fun", "cheerful", "colorful", "surprise", "gift"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "blue",
    size: "medium",
    description:
      "A lively arrangement bursting with color and energy, just like a birthday should be! Perfect for surprising someone special, these birthday flowers bring joy, laughter, and heartfelt wishes in every bloom.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "50",
    name: "Birthday Blossoms",
    category: "Birthday",
    price: 700,
    image: "/bouquets/bouquet-flower26.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["birthday", "elegant", "luxury", "roses", "celebration", "special"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "A sophisticated floral arrangement crafted with elegance and charm. Perfect for milestone birthdays or when you want to celebrate in style, this bouquet adds a touch of luxury to their special day.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "51",
    name: "Blooming Wishes",
    category: "Birthday",
    price: 1500,
    image: "/bouquets/bouquet-flower17.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["birthday", "fun", "cheerful", "colorful", "surprise", "gift"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "orange",
    size: "large",
    description:
      "A lively arrangement bursting with color and energy, just like a birthday should be! Perfect for surprising someone special, these birthday flowers bring joy, laughter, and heartfelt wishes in every bloom.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "52",
    name: "Birthday Elegance",
    category: "Birthday",
    prices: {
      small: 1000,
      medium: 1500,
      large: 2000,
      extraLarge: 2500,
    },
    image: "/bouquets/bouquet-flower22.jpg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["birthday", "fun", "cheerful", "colorful", "surprise", "gift"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A lively arrangement bursting with color and energy, just like a birthday should be! Perfect for surprising someone special, these birthday flowers bring joy, laughter, and heartfelt wishes in every bloom.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "53",
    name: "Healing Blooms",
    category: "Get Well Soon",
    price: 600,
    image: "/arrangements-in-vases-boxes/flower13.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: [
      "get-well-soon",
      "cheerful",
      "comfort",
      "bright",
      "uplifting",
      "flowers",
      "positive-energy",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A bright and cheerful arrangement designed to bring comfort, positivity, and hope. Perfect for wishing someone a speedy recovery, these fresh blooms lift the spirit and fill the room with warmth and joy.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "54",
    name: "Morning Joy",
    category: "Everyday",
    price: 400,
    image: "/bouquets/bouquet-flower1.jpg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["everyday", "bright", "cheerful", "casual", "fresh", "colorful"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A joyful mix of fresh blooms, perfect for brightening up your home, office, or gifting on any occasion. These everyday flowers bring color, warmth, and happiness into every moment.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "55",
    name: "Celebration in Bloom",
    category: "Everyday",
    price: 2000,
    image: "/arrangements-in-vases-boxes/flower46.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["decor", "event", "stylish", "flowers", "arrangement", "luxury"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful arrangement designed to elevate spaces with timeless beauty. Perfect for home décor, office styling, or event decoration, these flowers bring elegance and warmth to any setting.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "56",
    name: "Bloom & Brighten",
    category: "Everyday",
    price: 600,
    image: "/bouquets/bouquet-flower8.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["everyday", "flowers", "bright", "mixed", "gift", "uplifting"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "blue,yellow",
    size: "medium",
    description:
      "A radiant arrangement designed to start the day with a smile. With vibrant colors and uplifting blooms, this bouquet is ideal for everyday gifting and spontaneous surprises.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "57",
    name: "Bloom & Brighten",
    category: "Everyday",
    price: 700,
    image: "/bouquets/bouquet-flower9.jpeg",
    inStock: true,
    stock: 20,
    rating: 4.9,
    tags: ["everyday", "joy", "colorful", "simple", "casual", "happy"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink,yellow",
    size: "medium",
    description:
      "A radiant arrangement designed to start the day with a smile. With vibrant colors and uplifting blooms, this bouquet is ideal for everyday gifting and spontaneous surprises.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "58",
    name: "Bloom & Brighten",
    category: "Everyday",
    price: 600,
    image: "/bouquets/bouquet-flower10.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: ["everyday", "joy", "colorful", "simple", "casual", "happy"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "small",
    description:
      "A radiant arrangement designed to start the day with a smile. With vibrant colors and uplifting blooms, this bouquet is ideal for everyday gifting and spontaneous surprises.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "59",
    name: "Bloom & Brighten",
    category: "Everyday",
    price: 500,
    image: "/bouquets/bouquet-flower11.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["everyday", "bright", "cheerful", "casual", "fresh", "colorful"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "small",
    description:
      "A radiant arrangement designed to start the day with a smile. With vibrant colors and uplifting blooms, this bouquet is ideal for everyday gifting and spontaneous surprises.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "60",
    name: "Daily Blossoms",
    category: "Everyday",
    price: 600,
    image: "/bouquets/bouquet-flower12.jpeg",
    inStock: true,
    stock: 25,
    rating: 5,
    tags: ["everyday", "bright", "cheerful", "casual", "fresh", "colorful"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "orange,brown",
    size: "medium",
    description:
      "A joyful mix of fresh blooms, perfect for brightening up your home, office, or gifting on any occasion. These everyday flowers bring color, warmth, and happiness into every moment.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "61",
    name: "Bloom & Brighten",
    category: "Everyday",
    price: 800,
    image: "/bouquets/bouquet-flower13.jpeg",
    inStock: true,
    stock: 25,
    rating: 5,
    tags: ["everyday", "flowers", "bright", "mixed", "gift", "uplifting"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white,black,yellow,red",
    size: "medium",
    description:
      "An uplifting bouquet of mixed flowers that adds a touch of beauty to daily life. Perfect for any occasion or just because, these blooms bring light and happiness to every space.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "62",
    name: "Bloom & Brighten",
    category: "Everyday",
    price: 1500,
    image: "/bouquets/bouquet-flower14.jpeg",
    inStock: true,
    stock: 10,
    rating: 5,
    tags: ["everyday", "bright", "cheerful", "casual", "fresh", "colorful"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "purple",
    size: "medium",
    description:
      "A joyful mix of fresh blooms, perfect for brightening up your home, office, or gifting on any occasion. These everyday flowers bring color, warmth, and happiness into every moment.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "63",
    name: "Celebration in Bloom",
    category: "Everyday",
    price: 2000,
    image: "/arrangements-in-vases-boxes/flower43.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["decor", "event", "stylish", "flowers", "arrangement", "luxury"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful arrangement designed to elevate spaces with timeless beauty. Perfect for home décor, office styling, or event decoration, these flowers bring elegance and warmth to any setting.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "64",
    name: "Morning Joy",
    category: "Everyday",
    price: 800,
    image: "/bouquets/bouquet-flower15.jpeg",
    inStock: true,
    stock: 10,
    rating: 5,
    tags: ["everyday", "bright", "cheerful", "casual", "fresh", "colorful"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "A joyful mix of fresh blooms, perfect for brightening up your home, office, or gifting on any occasion. These everyday flowers bring color, warmth, and happiness into every moment.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "65",
    name: "Daily Blossoms",
    category: "Everyday",
    price: 600,
    image: "/bouquets/bouquet-flower24.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: ["everyday", "bright", "cheerful", "casual", "fresh", "colorful"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red,blue,pink",
    size: "medium",
    description:
      "A joyful mix of fresh blooms, perfect for brightening up your home, office, or gifting on any occasion. These everyday flowers bring color, warmth, and happiness into every moment.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "66",
    name: "Daily Blossoms",
    category: "Everyday",
    price: 600,
    image: "/bouquets/bouquet-flower40.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: ["everyday", "joy", "colorful", "simple", "casual", "happy"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red and yellow",
    size: "medium",
    description:
      "A radiant arrangement designed to start the day with a smile. With vibrant colors and uplifting blooms, this bouquet is ideal for everyday gifting and spontaneous surprises.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "67",
    name: "Bloom & Brighten",
    category: "Everyday",
    price: 2000,
    image: "/bouquets/bouquet-flower29.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: ["everyday", "joy", "colorful", "simple", "casual", "happy"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red and white",
    size: "medium",
    description:
      "A radiant arrangement designed to start the day with a smile. With vibrant colors and uplifting blooms, this bouquet is ideal for everyday gifting and spontaneous surprises.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "68",
    name: "Daily Blossoms",
    category: "Everyday",
    price: 2000,
    image: "/bouquets/bouquet-flower49.jpeg",
    inStock: true,
    stock: 10,
    rating: 5,
    tags: ["everyday", "cheerful", "bright", "casual", "colorful", "fresh"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "large",
    description:
      "A joyful mix of fresh blooms, perfect for brightening up your home, office, or gifting on any occasion. These everyday flowers bring color, warmth, and happiness into every moment.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "69",
    name: "Morning Joy",
    category: "Everyday",
    price: 1000,
    image: "/bouquets/bouquet-flower31.jpeg",
    inStock: true,
    stock: 25,
    rating: 5,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "yellow",
    size: "medium",
    description:
      "A radiant arrangement designed to start the day with a smile. With vibrant colors and uplifting blooms, this bouquet is ideal for everyday gifting and spontaneous surprises.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "70",
    name: "Bloom & Brighten",
    category: "Everyday",
    price: 1000,
    image: "/bouquets/bouquet-flower45.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["everyday", "joy", "colorful", "simple", "casual", "happy"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "yellow and green",
    size: "medium",
    description:
      "A radiant arrangement designed to start the day with a smile. With vibrant colors and uplifting blooms, this bouquet is ideal for everyday gifting and spontaneous surprises.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "71",
    name: "Blooming Success",
    category: "Congratulations",
    price: 1000,
    image: "/bouquets/bouquet-flower33.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: [
      "congratulations",
      "celebration",
      "success",
      "vibrant",
      "colorful",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "purple",
    size: "large",
    description:
      "A vibrant bouquet bursting with lively colors, designed to celebrate achievements and milestones. Perfect for graduations, promotions, or any joyful occasion, these blooms say “Congratulations” in the brightest way.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "72",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1500,
    image: "/bouquets/bouquet-flower32.jpeg",
    inStock: true,
    stock: 25,
    rating: 5,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "73",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1500,
    image: "/bouquets/bouquet-flower44.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "74",
    name: "Colors of Celebration",
    category: "Congratulations",
    price: 1000,
    image: "/bouquets/bouquet-flower5.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: [
      "congratulations",
      "celebration",
      "success",
      "vibrant",
      "colorful",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "large",
    description:
      "A vibrant bouquet bursting with lively colors, designed to celebrate achievements and milestones. Perfect for graduations, promotions, or any joyful occasion, these blooms say “Congratulations” in the brightest way.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "75",
    name: "Blooming Success",
    category: "Congratulations",
    price: 2000,
    image: "/bouquets/bouquet-flower7.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: [
      "congratulations",
      "celebration",
      "success",
      "vibrant",
      "colorful",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink,red",
    size: "medium",
    description:
      "A vibrant bouquet bursting with lively colors, designed to celebrate achievements and milestones. Perfect for graduations, promotions, or any joyful occasion, these blooms say “Congratulations” in the brightest way.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "76",
    name: "Colors of Celebration",
    category: "Congratulations",
    price: 2000,
    image: "/bouquets/bouquet-flower43.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: [
      "congratulations",
      "celebration",
      "success",
      "vibrant",
      "colorful",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink,red",
    size: "medium",
    description:
      "A vibrant bouquet bursting with lively colors, designed to celebrate achievements and milestones. Perfect for graduations, promotions, or any joyful occasion, these blooms say “Congratulations” in the brightest way.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "77",
    name: "Colors of Celebration",
    category: "Congratulations",
    price: 1500,
    image: "/bouquets/bouquet-flower17.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: [
      "congratulations",
      "celebration",
      "success",
      "vibrant",
      "colorful",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink,red",
    size: "medium",
    description:
      "A vibrant bouquet bursting with lively colors, designed to celebrate achievements and milestones. Perfect for graduations, promotions, or any joyful occasion, these blooms say “Congratulations” in the brightest way.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "78",
    name: "Cheers in Bloom",
    category: "Congratulations",
    price: 3000,
    image: "/bouquets/bouquet-flower39.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: [
      "congratulations",
      "celebration",
      "success",
      "vibrant",
      "colorful",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "purple",
    size: "medium",
    description:
      "A vibrant bouquet bursting with lively colors, designed to celebrate achievements and milestones. Perfect for graduations, promotions, or any joyful occasion, these blooms say “Congratulations” in the brightest way.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "79",
    name: "Cheers in Bloom",
    category: "Congratulations",
    price: 1500,
    image: "/bouquets/bouquet-flower34.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: [
      "congratulations",
      "celebration",
      "success",
      "vibrant",
      "colorful",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "blue,yellow",
    size: "medium",
    description:
      "A vibrant bouquet bursting with lively colors, designed to celebrate achievements and milestones. Perfect for graduations, promotions, or any joyful occasion, these blooms say “Congratulations” in the brightest way.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "80",
    name: "Celebration Elegance",
    category: "Event and Decor",
    price: 800,
    image: "/bouquets/bouquet-flower36.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: [
      "event",
      "celebration",
      "decor",
      "luxury",
      "festive",
      "special-occasion",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "blue,white",
    size: "medium",
    description:
      "A vibrant floral arrangement made to celebrate life’s special moments. Ideal for event décor, stage decoration, or festive gatherings, this bouquet creates a striking atmosphere of joy and sophistication.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "81",
    name: "Décor Charm Bouquet",
    category: "Event and Decor",
    price: 3000,
    image: "/bouquets/bouquet-flower37.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: [
      "event",
      "celebration",
      "decor",
      "luxury",
      "festive",
      "special-occasion",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "yellow",
    size: "large",
    description:
      "A vibrant floral arrangement made to celebrate life’s special moments. Ideal for event décor, stage decoration, or festive gatherings, this bouquet creates a striking atmosphere of joy and sophistication.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "82",
    name: "Wreath Flowers",
    category: "Sympathy and Condolence",
    price: 2000,
    image: "/Wreath/wreath-flower11.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["sympathy", "condolence", "comfort", "serenity", "white-lilies"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A serene condolence arrangement crafted with delicate white lilies and soft greenery. This elegant design conveys comfort, peace, and heartfelt support during times of loss, offering a gentle tribute of remembrance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "83",
    name: "Colors of Celebration",
    category: "Congratulations",
    price: 1000,
    image: "/bouquets/bouquet-flower20.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: [
      "congratulations",
      "celebration",
      "success",
      "vibrant",
      "colorful",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink,red,green",
    size: "medium",
    description:
      "A vibrant bouquet bursting with lively colors, designed to celebrate achievements and milestones. Perfect for graduations, promotions, or any joyful occasion, these blooms say “Congratulations” in the brightest way.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "84",
    name: "Colors of Celebration",
    category: "Congratulations",
    price: 700,
    image: "/bouquets/bouquet-flower19.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: [
      "congratulations",
      "celebration",
      "success",
      "vibrant",
      "colorful",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink,red",
    size: "medium",
    description:
      "A vibrant bouquet bursting with lively colors, designed to celebrate achievements and milestones. Perfect for graduations, promotions, or any joyful occasion, these blooms say “Congratulations” in the brightest way.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "85",
    name: "Peaceful Memories",
    category: "Sympathy and Condolence",
    price: 2000,
    image: "/Wreath/wreath-flower18.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["sympathy", "condolence", "comfort", "serenity", "white-lilies"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red,blue,green",
    size: "medium",
    description:
      "A serene condolence arrangement crafted with delicate white lilies and soft greenery. This elegant design conveys comfort, peace, and heartfelt support during times of loss, offering a gentle tribute of remembrance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "86",
    name: "Peaceful Memories",
    category: "Sympathy and Condolence",
    price: 3000,
    image: "/Wreath/wreath-flower19.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["sympathy", "condolence", "comfort", "serenity", "white-lilies"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A serene condolence arrangement crafted with delicate white lilies and soft greenery. This elegant design conveys comfort, peace, and heartfelt support during times of loss, offering a gentle tribute of remembrance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "87",
    name: "Hearts in Bloom",
    category: "Love and Romance",
    price: 800,
    image: "/Wreath/wreath-flower16.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A joyful bouquet of mixed romantic blooms, full of color and charm. Perfect for brightening your partner’s day and celebrating love in its most beautiful form.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "88",
    name: "Colors of Celebration",
    category: "Congratulations",
    price: 1800,
    image: "/arrangements-in-vases-boxes/flower41.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: [
      "congratulations",
      "celebration",
      "success",
      "vibrant",
      "colorful",
      "gift",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "pink",
    size: "medium",
    description:
      "A vibrant bouquet bursting with lively colors, designed to celebrate achievements and milestones. Perfect for graduations, promotions, or any joyful occasion, these blooms say “Congratulations” in the brightest way.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "89",
    name: "Tranquil Tribute",
    category: "Sympathy and Condolence",
    prices: {
      small: 700,
      medium: 1000,
      large: 1500,
    },
    image: "/Wreath/wreath-flower14.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: ["sympathy", "condolence", "comfort", "serenity", "white-lilies"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A serene condolence arrangement crafted with delicate white lilies and soft greenery. This elegant design conveys comfort, peace, and heartfelt support during times of loss, offering a gentle tribute of remembrance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "90",
    name: "Celebration Elegance",
    category: "Event and Decor",
    price: 1500,
    image: "/Wreath/wreath-flower20.jpg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: [
      "event",
      "celebration",
      "decor",
      "luxury",
      "festive",
      "special-occasion",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "yellow",
    size: "medium",
    description:
      "A graceful arrangement designed to elevate spaces with timeless beauty. Perfect for home décor, office styling, or event decoration, these flowers bring elegance and warmth to any setting.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "91",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1000,
    image: "/Fresh-Flower/fresh-flower1.jpg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "92",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1000,
    image: "/Fresh-Flower/fresh-flower2.jpg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "93",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1000,
    image: "/Fresh-Flower/fresh-flower3.jpg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "94",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 900,
    image: "/Fresh-Flower/fresh-flower5.jpg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "95",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 900,
    image: "/Fresh-Flower/fresh-flower6.jpg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "96",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 900,
    image: "/Fresh-Flower/fresh-flower7.jpg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "97",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 900,
    image: "/Fresh-Flower/fresh-flower8.jpg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "98",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1000,
    image: "/Fresh-Flower/fresh-flower11.jpg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "99",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1500,
    image: "/Fresh-Flower/fresh-flower15.jpeg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "red",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "100",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1000,
    image: "/Bridal Bouquet/bridal-bouquet-flower2.jpg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "101",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 900,
    image: "/Bridal Bouquet/bridal-bouquet-flower3.jpg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "102",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 900,
    image: "/Bridal Bouquet/bridal-bouquet-flower4.jpg",
    inStock: true,
    stock: 15,
    rating: 4,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white and purple",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "103",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1000,
    image: "/Bridal Bouquet/bridal-bouquet-flower5.jpg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "104",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 800,
    image: "/Bridal Bouquet/bridal-bouquet-flower6.jpg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: ["romantic", "classic", "red"],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A classic arrangement of 12 long-stemmed red roses, perfect for expressing love and romance.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "105",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 2500,
    image: "/Bridal Bouquet/bridal-bouquet-flower7.jpg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white,red",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "106",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1000,
    image: "/Bridal Bouquet/bridal-bouquet-flower8.jpeg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "107",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1200,
    image: "/Bridal Bouquet/bridal-bouquet-flower10.jpeg",
    inStock: true,
    stock: 15,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "108",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 800,
    image: "/Bridal Bouquet/bridal-bouquet-flower11.jpeg",
    inStock: true,
    stock: 15,
    rating: 5,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "109",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1000,
    image: "/Bridal Bouquet/bridal-bouquet-flower12.jpeg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "110",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1000,
    image: "/Bridal Bouquet/bridal-bouquet-flower13.jpeg",
    inStock: true,
    stock: 25,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "111",
    name: "Bridal Bliss Bouquet",
    category: "Bridal",
    price: 1500,
    image: "/Bridal Bouquet/bridal-bouquet-flower14.jpeg",
    inStock: true,
    stock: 10,
    rating: 4.9,
    tags: [
      "bridal",
      "wedding",
      "romantic",
      "elegant",
      "bouquet",
      "love",
      "special-day",
    ],
    careInstructions: "Keep in cool water, trim stems daily",
    season: "year-round",
    color: "white",
    size: "medium",
    description:
      "A graceful bridal bouquet designed to complement the beauty of the bride on her special day. Crafted with elegant blooms in soft romantic tones, this bouquet symbolizes love, purity, and everlasting happiness.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
